name       : alacritty
version    : 0.12.1
release    : 24
source     :
    - https://github.com/alacritty/alacritty/archive/refs/tags/v0.12.1.tar.gz : 14bce0bfc538872c97e0e38b9233a9d1fa992dcf83a22b6035da5fe58a55bc6c
license    : Apache-2.0
component  : system.utils
summary    : A cross-platform, GPU-accelerated terminal emulator
description: |
    Alacritty is the fastest terminal emulator in existence.
    Using the GPU for rendering enables optimizations that simply aren't possible in other emulators.
homepage   : https://alacritty.org
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - cargo
build      : |
    make binary
install    : |
    install -Dm00755 target/release/alacritty -t $installdir/usr/bin
    install -Dm00644 alacritty.yml -t $installdir/usr/share/alacritty/

    install -Dm00644 extra/completions/alacritty.bash $installdir/usr/share/bash-completion/completions/alacritty
    install -Dm00644 extra/completions/_alacritty $installdir/usr/share/zsh/site-functions/_alacritty
    install -Dm00644 extra/completions/alacritty.fish $installdir/usr/share/fish/vendor_completions.d/alacritty.fish

    install -Dm00644 extra/linux/Alacritty.desktop $installdir/usr/share/applications/alacritty.desktop
    install -Dm00644 extra/alacritty.man $installdir/usr/share/man/man1/alacritty.1
    install -Dm00644 extra/logo/alacritty-term+scanlines.svg $installdir/usr/share/icons/hicolor/scalable/apps/Alacritty.svg
