name       : alacritty
version    : 0.3.0
release    : 4
source     :
    - https://github.com/jwilm/alacritty/archive/v0.3.0.tar.gz : 62f96fa751eb553012dc7e562e62cdf37c6668c8117be31790ce7dc2d4d28a47
license    : Apache-2.0
component  : system.utils
summary    : A cross-platform, GPU-accelerated terminal emulator
description: |
    Alacritty is the fastest terminal emulator in existence.
    Using the GPU for rendering enables optimizations that simply aren't possible in other emulators.
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - cargo
build      : |
    make binary
install    : |
    install -Dm00755 target/release/alacritty -t $installdir/usr/bin
    install -Dm00644 alacritty.yml -t $installdir/usr/share/alacritty/

    mkdir -p $installdir/usr/share/terminfo/a
    tic -o $installdir/usr/share/terminfo/a -e alacritty,alacritty-direct extra/alacritty.info

    install -Dm00644 extra/completions/alacritty.bash $installdir/usr/share/bash-completion/completion/alacritty
    install -Dm00644 extra/completions/_alacritty $installdir/usr/share/zsh/site-functions/_alacritty
    install -Dm00644 extra/completions/alacritty.fish $installdir/usr/share/fish/vendor_completions.d/alacritty

    install -Dm00644 extra/linux/alacritty.desktop $installdir/usr/share/applications/alacritty.desktop
    install -Dm00644 extra/alacritty.man $installdir/usr/share/man/man1/alacritty.1
    install -Dm00644 extra/logo/alacritty-term+scanlines.svg $installdir/usr/share/icons/hicolor/scalable/apps/Alacritty.svg
