name       : alacritty
version    : 0.2.4
release    : 1
source     :
    - https://github.com/jwilm/alacritty/archive/v0.2.4.tar.gz : f2d2bf02ffa538fb94e9679260be9c32e52fa4e81d36b8005700fc8b30a84761
license    : Apache-2.0
component  : system.utils
summary    : A cross-platform, GPU-accelerated terminal emulator
description: |
    Alacritty is the fastest terminal emulator in existence.
    Using the GPU for rendering enables optimizations that simply aren't possible in other emulators.
networking : yes
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - cargo
build      : |
    cargo update
    cargo build --release
install    : |
    install -Dm00755 target/release/alacritty -t $installdir/usr/bin
    install -Dm00644 alacritty.yml -t $installdir/usr/share/alacritty/

    mkdir -p $installdir/usr/share/terminfo/a
    tic -o $installdir/usr/share/terminfo/a -e alacritty,alacritty-direct alacritty.info

    install -Dm00644 alacritty-completions.bash $installdir/usr/share/bash-completion/completion/alacritty
    install -Dm00644 alacritty-completions.zsh $installdir/usr/share/zsh/site-functions/_alacritty
    install -Dm00644 alacritty-completions.fish $installdir/usr/share/fish/vendor_completions.d/alacritty

    install -Dm00644 alacritty.desktop $installdir/usr/share/applications/alacritty.desktop
    install -Dm00644 alacritty.man $installdir/usr/share/man/man1/alacritty.1
